# -*- coding: utf-8 -*-
"""modelo_trigo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smkbet12Izjtj2cC0VnOCTWLUhMLoM0v
"""

# =============================================================
# 1. IMPORTS
# =============================================================
import pandas as pd
import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, r2_score
from statsmodels.tsa.statespace.sarimax import SARIMAX
from xgboost import XGBRegressor

BASE = Path(".")

# =============================================================
# 2. SERIE PRINCIPAL ARGENTINA
# =============================================================
trigo = pd.read_excel(BASE/"Trigo_Ajustado_MENSUAL_ONLY.xlsx")
trigo['PeriodoYM'] = pd.to_datetime(trigo['PeriodoYM'])
trigo = trigo.sort_values('PeriodoYM').reset_index(drop=True)
trigo['Mes'] = trigo['PeriodoYM'].dt.month

# =============================================================
# 3. FUTUROS USA
# =============================================================
fut = pd.read_csv(BASE/"Datos históricos Futuros trigo EE.UU..csv")
fut['Fecha'] = pd.to_datetime(fut['Fecha'], format="%d.%m.%Y")

fut['Cierre'] = (
    fut['Cierre'].astype(str)
                 .str.strip()
                 .str.replace(',', '', regex=False)
)
fut['Cierre'] = pd.to_numeric(fut['Cierre'], errors='coerce')

fut['PeriodoYM'] = fut['Fecha'].values.astype("datetime64[M]")

fut_m = (fut.sort_values('Fecha')
             .groupby('PeriodoYM')['Cierre']
             .last()
             .reset_index()
             .rename(columns={'Cierre':'Futuro_USA'}))

# =============================================================
# 4. USD/ARS
# =============================================================
usd = pd.read_csv(BASE/"Datos históricos USD_ARS (1).csv")
usd['Fecha'] = pd.to_datetime(usd['Fecha'], format="%d.%m.%Y")

usd['Cierre'] = (
    usd['Cierre'].astype(str)
                 .str.strip()
                 .str.replace(',', '', regex=False)
)
usd['Cierre'] = pd.to_numeric(usd['Cierre'], errors='coerce')

usd['PeriodoYM'] = usd['Fecha'].values.astype("datetime64[M]")

usd_m = (usd.sort_values('Fecha')
             .groupby('PeriodoYM')['Cierre']
             .last()
             .reset_index()
             .rename(columns={'Cierre':'USD_ARS'}))

# =============================================================
# 5. MERGE BÁSICO + FEATURES
# =============================================================
data = (
    trigo
      .merge(fut_m, on='PeriodoYM', how='left')
      .merge(usd_m, on='PeriodoYM', how='left')
)

data = data.sort_values('PeriodoYM').reset_index(drop=True)

# Tendencia temporal
data['t'] = np.arange(len(data))

# Logaritmos
data = data.dropna(subset=['Precio_Hoy','Futuro_USA','USD_ARS']).copy()
data['log_precio'] = np.log(data['Precio_Hoy'])
data['log_fut']    = np.log(data['Futuro_USA'])
data['log_usd']    = np.log(data['USD_ARS'])

# Seteamos índice en fecha para ARIMA
data = data.set_index('PeriodoYM')

# =============================================================
# 6. MODELO ARIMA SOLO SOBRE log_precio
# =============================================================
y = data['log_precio']

arima = SARIMAX(
    y,
    order=(1,1,1),
    seasonal_order=(1,0,1,12),
    enforce_stationarity=False,
    enforce_invertibility=False
)

res_arima = arima.fit(disp=False)

# Predicción en toda la muestra (one-step ahead approx.)
arima_pred = res_arima.get_prediction().predicted_mean
residuals  = y - arima_pred
data['resid_arima'] = residuals

# =============================================================
# 7. FEATURES PARA XGBOOST (modelo de residuos)
# =============================================================

df = data.copy()

# Lags del residuo
for lag in range(1,7):
    df[f'resid_lag{lag}'] = df['resid_arima'].shift(lag)

# Mes como dummies
df['Mes'] = df.index.month
df = pd.get_dummies(df, columns=['Mes'], drop_first=True)

# Nos quedamos con filas sin NaN
df_model = df.dropna(subset=['resid_arima','log_fut','log_usd'])

feature_cols = ['log_fut','log_usd','t'] + [f'resid_lag{lag}' for lag in range(1,7)]
feature_cols += [c for c in df_model.columns if c.startswith('Mes_')]

X_res = df_model[feature_cols]
y_res = df_model['resid_arima']

# =============================================================
# 8. TRAIN / TEST SPLIT (últimos 12 meses para test)
# =============================================================
test_horizon = 12
X_res_train, X_res_test = X_res.iloc[:-test_horizon], X_res.iloc[-test_horizon:]
y_res_train, y_res_test = y_res.iloc[:-test_horizon], y_res.iloc[-test_horizon:]

# ARIMA pred alineado con df_model
arima_aligned = arima_pred.reindex(df_model.index)
arima_test    = arima_aligned.iloc[-test_horizon:]

# =============================================================
# 9. XGBOOST PARA RESIDUOS
# =============================================================
xgb = XGBRegressor(
    n_estimators=600,
    max_depth=6,
    learning_rate=0.03,
    subsample=0.9,
    colsample_bytree=0.9,
    objective='reg:squarederror',
    random_state=0
)

xgb.fit(X_res_train, y_res_train)

res_test_pred = xgb.predict(X_res_test)

# Pred final en log-precio = ARIMA + residuo ML
log_pred_final_test = arima_test + res_test_pred
log_real_test       = y.reindex(df_model.index).iloc[-test_horizon:]

precio_pred_test = np.exp(log_pred_final_test)
precio_real_test = np.exp(log_real_test)

print("MAE test (nivel de precio):", mean_absolute_error(precio_real_test, precio_pred_test))
print("R2 test (log-precio):", r2_score(log_real_test, log_pred_final_test))

# =============================================================
# 10. GRÁFICO TEST (últimos 12 meses)
# =============================================================
fechas_test = log_real_test.index

plt.figure(figsize=(10,5))
plt.plot(fechas_test, precio_real_test.values, label="Real")
plt.plot(fechas_test, precio_pred_test.values, label="Predicho híbrido ARIMA+XGB")
plt.legend()
plt.xticks(rotation=45)
plt.ylabel("Precio_Hoy (ARS constantes)")
plt.title("Precio trigo AR - Test 12 meses (híbrido ARIMA + XGBoost)")
plt.tight_layout()
plt.show()

# =============================================================
# 11. PRONÓSTICO 12 MESES ADELANTE
# =============================================================

# 11.1 Forecast ARIMA puro
steps_ahead = 12
forecast_arima = res_arima.get_forecast(steps=steps_ahead)
log_arima_future_raw = forecast_arima.predicted_mean

# Fechas futuras según la serie original
last_date = df_model.index[-1]
future_dates = pd.date_range(
    start=last_date + pd.offsets.MonthBegin(1),
    periods=steps_ahead,
    freq='MS'
)

# Reindexamos el forecast ARIMA a esas fechas
log_arima_future = pd.Series(log_arima_future_raw.values, index=future_dates)

# 11.2 Forecast de residuos con XGBoost (escenario Chicago y USD constantes)
last_row = df_model.iloc[-1]

# lags iniciales del residuo
res_lags = [last_row[f'resid_lag{lag}'] for lag in range(1,7)]
future_resids = []

for step, fecha in enumerate(future_dates, start=1):
    mes = fecha.month

    feat = {
        'log_fut': last_row['log_fut'],   # escenario estable
        'log_usd': last_row['log_usd'],
        't'      : last_row['t'] + step,
    }

    # lags del residuo
    for i, val in enumerate(res_lags, start=1):
        feat[f'resid_lag{i}'] = val

    # dummies de mes
    for c in [c for c in df_model.columns if c.startswith('Mes_')]:
        feat[c] = 0
    if f'Mes_{mes}' in feat:
        feat[f'Mes_{mes}'] = 1

    X_fut = pd.DataFrame([feat])[feature_cols]
    pred_res = xgb.predict(X_fut)[0]
    future_resids.append(pred_res)

    # actualizamos lags (nuevo residuo adelante)
    res_lags = [pred_res] + res_lags[:-1]

log_resid_future = pd.Series(future_resids, index=future_dates)

# 11.3 Pred final future = ARIMA future + residuo future
log_precio_future = log_arima_future + log_resid_future
precio_future = np.exp(log_precio_future)

forecast_df = pd.DataFrame({
    'PeriodoYM': future_dates,
    'Precio_Pronosticado': precio_future.values
})


# =============================================================
# 12. HISTÓRICO + PRONÓSTICO
# =============================================================
plt.figure(figsize=(12,5))
hist_tail = data.reset_index().tail(36)  # últimos 3 años aprox.
plt.plot(hist_tail['PeriodoYM'], np.exp(hist_tail['log_precio']), label="Histórico")

plt.plot(forecast_df['PeriodoYM'], forecast_df['Precio_Pronosticado'],
         marker='o', linestyle='--', label="Pronóstico 12 meses (híbrido)")
plt.xticks(rotation=45)
plt.ylabel("Precio_Hoy (ARS constantes)")
plt.title("Precio trigo AR - Histórico reciente y pronóstico 12 meses (ARIMA + XGBoost)")
plt.legend()
plt.tight_layout()
plt.show()